server:
  port: 8080
spring:
  application:
    name: sm
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.36.63.55:3306/sm
    username: root
    password: wenxin
  redis:
    database: 1
    host: 121.36.63.55
    password: wenxin
    port: 6379
    lettuce:
      pool:
        max-wait: -1ms

  #邮件配置
  mail:
    host: smtp.163.com
    port: 465
    protocol: smtps
    username: wenxin_web@163.com
    password: YCOUPMDBKDTQRAJR
                                                          

root-path: ${user.dir}
image-path: ${root-path}/image/